import type { Metadata } from "next";
import classNames from "classnames";
import { Fira_Code as FiraCode } from "next/font/google";
import hljs from "highlight.js/lib/core";
import javascript from "highlight.js/lib/languages/javascript";
import typescript from "highlight.js/lib/languages/typescript";
import syntaxThemeGithubDark from "./syntax_themes/github-dark.module.css";

hljs.registerLanguage("javascript", javascript);
hljs.registerLanguage("typescript", typescript);

const firaCode = FiraCode({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.ReactNode {
  return (
    <div>
      <div className={classNames(syntaxThemeGithubDark, firaCode.className)}>
        {children}
      </div>
    </div>
  );
}
